# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [1]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [2]:
#your code here
df_res = pd.DataFrame()
for i in range(10):
  file_path_students = f'/content/Students_info_{i}.csv'
  file_path_marks = f'/content/Students_marks_{i}.csv'
  df_students =pd.read_csv(file_path_students)
  df_marks = pd.read_csv(file_path_marks)
  df_temp = df_students.merge(df_marks, on='index', how='left')
  df_res = pd.concat([df_res, df_temp])

In [3]:
df_res

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
95,995,female,group E,master's degree,standard,completed,group10,88,99,95
96,996,male,group C,high school,free/reduced,none,group10,62,55,55
97,997,female,group C,high school,free/reduced,completed,group10,59,71,65
98,998,female,group D,some college,standard,completed,group10,68,78,77
99,999,female,group D,some college,free/reduced,none,group10,77,86,86

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [ ]:
del df_res['index']
df_res.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [ ]:
df_res.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
df_res.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [ ]:
df_res.isna().any()

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course        False
group                          False
math score                     False
reading score                  False
writing score                  False
dtype: bool

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [ ]:
df_res[['math score', 'writing score', 'reading score']].mean()

math score       66.089
writing score    68.054
reading score    69.169
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [ ]:
df_res[df_res['test preparation course'] == 'completed'][['math score', 'reading score', 'writing score']].mean()

math score       69.695531
reading score    73.893855
writing score    74.418994
dtype: float64

In [ ]:
df_res[df_res['test preparation course'] == 'none'][['math score', 'reading score', 'writing score']].mean()

math score       64.077882
reading score    66.534268
writing score    64.504673
dtype: float64

**Во всех 3-ех предметах студенты, прошедшие курс получили балл выше, разница от 5 до 10 баллов**👍👍👍👍👍👍👍

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [ ]:
df_res['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [ ]:
df_res.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"}, inplace = True)
df_res

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95
96,male,group C,high school,free/reduced,none,group10,62,55,55
97,female,group C,high school,free/reduced,completed,group10,59,71,65
98,female,group D,some college,standard,completed,group10,68,78,77
99,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [ ]:
print(len(df_res[df_res['math score'] >= 50])/len(df_res))
print(len(df_res[(df_res['test preparation'] == 'completed') & (df_res['math score'] >= 50)])/len(df_res[df_res['test preparation'] == 'completed']))
print(len(df_res[(df_res['test preparation'] == 'none') & (df_res['math score'] < 50) & (df_res['gender'] == 'female')])/len(df_res[(df_res['test preparation'] == 'none') & (df_res['gender'] == 'female')]))

0.865
0.9217877094972067
0.20958083832335328

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
%%time
df_res.groupby('race/ethnicity')['reading score'].mean()

CPU times: user 1.42 ms, sys: 895 µs, total: 2.31 ms
Wall time: 7.74 ms

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

In [ ]:
%%time
df_res.groupby('education')['writing score'].min()

CPU times: user 2.16 ms, sys: 0 ns, total: 2.16 ms
Wall time: 3.33 ms

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [ ]:
%%time
for elem in (df_res['race/ethnicity'].unique()):
  df_help = df_res[df_res['race/ethnicity'] == elem]
  print(elem, df_help.loc[:, 'reading score'].mean())

group B 67.35263157894737
group C 69.10344827586206
group A 64.67415730337079
group D 70.03053435114504
group E 73.02857142857142
CPU times: user 6.98 ms, sys: 1 ms, total: 7.98 ms
Wall time: 8.1 ms

In [ ]:
%%time
for elem in (df_res['education'].unique()):
  df_help = df_res[df_res['education'] == elem]
  print(elem, df_help.loc[:, 'writing score'].min())

bachelor's degree 38
some college 19
master's degree 46
associate's degree 35
high school 15
some high school 10
CPU times: user 9.32 ms, sys: 0 ns, total: 9.32 ms
Wall time: 9.55 ms

**Видим, что groupby работает примерно в 4 раза быстрее цикла, кайф** 👍👍👍👍👍👍👍

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [ ]:
grouped = pd.pivot_table(df_res, index=['gender','education'])
grouped

<ipython-input-36-441d110a5283>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  grouped = pd.pivot_table(df_res, index=['gender','education'])

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
import numpy as np
df_res['Math_PassStatus'] = np.where(df_res['math score'] >= 50, 'P', 'F')
df_res

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P
1,female,group C,some college,standard,completed,group1,69,90,88,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F
4,male,group C,some college,standard,none,group1,76,78,75,P
...,...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95,P
96,male,group C,high school,free/reduced,none,group10,62,55,55,P
97,female,group C,high school,free/reduced,completed,group10,59,71,65,P
98,female,group D,some college,standard,completed,group10,68,78,77,P
99,female,group D,some college,free/reduced,none,group10,77,86,86,P

In [ ]:
print((df_res['math score'] >= 50).sum())
print((df_res['math score'] < 50).sum())

865
135

In [ ]:
df_res['Reading_PassStatus'] = np.where(df_res['reading score'] >= 50, 'P', 'F')
df_res

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P
4,male,group C,some college,standard,none,group1,76,78,75,P,P
...,...,...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95,P,P
96,male,group C,high school,free/reduced,none,group10,62,55,55,P,P
97,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P
98,female,group D,some college,standard,completed,group10,68,78,77,P,P
99,female,group D,some college,free/reduced,none,group10,77,86,86,P,P

In [ ]:
print((df_res['reading score'] >= 50).sum())
print((df_res['reading score'] < 50).sum())

910
90

In [ ]:
df_res['Writing_PassStatus'] = np.where(df_res['writing score'] >= 50, 'P', 'F')
df_res

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P
96,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P
97,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P
98,female,group D,some college,standard,completed,group10,68,78,77,P,P,P
99,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P

In [ ]:
print((df_res['writing score'] >= 50).sum())
print((df_res['writing score'] < 50).sum())

886
114

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
df_res['OverAll_PassStatus'] = np.where((df_res['writing score'] >= 50) & (df_res['reading score'] >= 50) & (df_res['math score'] >= 50), 'P', 'F')
df_res

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P
96,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P
97,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P
98,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P
99,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P

In [ ]:
((df_res['writing score'] >= 50) & (df_res['reading score'] >= 50) & (df_res['math score'] >= 50)).sum()

812

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [7]:

def GetGrade(average_mark):
  if average_mark < 50:
    return 'F'
  if (average_mark >= 50) & (average_mark <= 60):
    return 'E'
  if (average_mark >= 60) & (average_mark <= 70):
    return 'D'
  if (average_mark >= 70) & (average_mark <= 80):
    return 'C'
  if (average_mark >= 80) & (average_mark <= 90):
    return 'B'
  if average_mark > 90:
    return 'A'
a = (df_res['math score'] + df_res['reading score'] + df_res['writing score'])/3
df_res['Grade'] = a.apply(GetGrade)
df_res

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score,Grade
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74,C
1,1,female,group C,some college,standard,completed,group1,69,90,88,B
2,2,female,group B,master's degree,standard,none,group1,90,95,93,A
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F
4,4,male,group C,some college,standard,none,group1,76,78,75,C
...,...,...,...,...,...,...,...,...,...,...,...
95,995,female,group E,master's degree,standard,completed,group10,88,99,95,A
96,996,male,group C,high school,free/reduced,none,group10,62,55,55,E
97,997,female,group C,high school,free/reduced,completed,group10,59,71,65,D
98,998,female,group D,some college,standard,completed,group10,68,78,77,C
99,999,female,group D,some college,free/reduced,none,group10,77,86,86,B

In [8]:
df_res['Grade'].value_counts()

D    260
C    253
E    190
B    144
F    103
A     50
Name: Grade, dtype: int64